app:
  search:
    pagination:
      numberRecords:
        default: 10
        max: 100

spring:
  application.name: exemplo-kotlin-springboot-graphql
  h2.console:
    enabled: true
    path: /h2-console
  jpa.hibernate.ddl-auto: validate

# Configuração de log.
logging:
  level:
    org:
      apache.http: INFO
      springframework: INFO
      spring: INFO
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    com:
      andrejustiandre: INFO
      andrejusti.example.kotlin.springboot.graphql.infrastructure.exception.ValidationException: OFF
